# Generated by Django 3.2.12 on 2022-04-08 13:11

from django.db import migrations, models
from django_celery_beat.models import PeriodicTask, IntervalSchedule


class Migration(migrations.Migration):

    def create_tasks(apps, schema_editor):
        schedule, created = IntervalSchedule.objects.get_or_create(
            every=1,
            period=IntervalSchedule.DAYS,
        )
        PeriodicTask.objects.create(
            interval=schedule,
            name="Парсинг лог-файла",
            task="aggregator.parse_logs_task",
            enabled=False,
        )
        PeriodicTask.objects.create(
            interval=schedule,
            name="Удалить все логи",
            task="aggregator.delete_all_logs_task",
            enabled=False,
        )

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='IP')),
                ('timestamp', models.CharField(blank=True, max_length=300, null=True, verbose_name='Время')),
                ('timezone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Временная зона')),
                ('request', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Запрос')),
                ('status', models.PositiveIntegerField(blank=True, null=True, verbose_name='Статус код')),
                ('bytes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Байты')),
                ('referer', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Referer')),
                ('useragent', models.CharField(blank=True, max_length=500, null=True, verbose_name='User-Agent')),
            ],
            options={
                'verbose_name': 'Лог файл',
                'verbose_name_plural': 'Лог файлы',
            },
        ),
        migrations.RunPython(create_tasks),
    ]
