# Generated by Django 3.2.12 on 2022-04-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logfile',
            options={'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterField(
            model_name='logfile',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время'),
        ),
    ]
