# Generated by Django 3.2.12 on 2022-04-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_auto_20220408_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logfile',
            name='timezone',
        ),
    ]
